# --- CONFIGURACIÓN DE RED  ---
# Puertos servidor Netty/KryoNet 
server.network.tcp.port=54555
server.network.udp.port=54777

# --- CACHÉ Y MATCHMAKING  ---
# servidor Redis
redis.host=localhost
redis.port=6379

# --- REGLAS DEL JUEGO  ---
game.match.min_players=2
game.match.max_players=4
game.economy.starting_coins=100
game.economy.ranked_entry_fee=50

# --- VERSIÓN ---
server.version=1.0.0-BETA